server:
  port: 8092
mybatis:
  mapper-locations: classpath:mapping/*.xml


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.123:3306/patriotism?useSSL=false
    username: root
    password: mysqladmin
    name: patriotism
    #连接池配置
    type: org.apache.commons.dbcp2.BasicDataSource

#    druid:
#      max-active: 20
#      initial-size: 1
#      max-wait: 60000
#      min-idle: 1
#      time-between-enviction-runs-millis: 60000

    #redis配置
  redis:
    database: 1
    host: 192.168.0.122
    port: 6379
    password: redis
    pool:
      max-active: 8   # 最大连接数
      max-wait: 1     # 最大阻塞等待时间
      max-idle: 8     # 最大空闲连接
      min-idle: 0     # 最小空闲连接
    timeout: 0        # 连接超时时间
  mail:
    host: smtp.163.com
    username: nightnessss@163.com
    password: W1948730080
    default-encoding: UTF-8
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html

security:
  basic:
    enabled: true

fehead:
  initialize:
    browser:
      telParameter: tel
      sendOtpCode: /send/otpCode
      formLoginUrl: /loginByForm
      otpLoginUrl: /loginByOtp
    smsProperties:
      appKey: LTAIqwxU8y65KvAg
      secret: 8UwBxCvhl9vpTR1IEv4LNiHrxvNTo5
      regionId: cn-hangzhou
      signName: 堆栈科技
      smsModel:
        - {name: SMS_171112301, des: 注册}
        - {name: SMS_171117329, des: 登录}
      smsNumber: 6
    sendEmailProperties:
      fromAddress: nightnessss@163.com



